"""Static metadata used by SAFIRA-SSA."""

from __future__ import annotations

PACKAGE_NAME = "safira-ssa"
PROJECT_NAME = "SAFIRA-SSA"
PROJECT_LONG_NAME = "Skill Advancement Forecasting and Intelligence for Readiness in Africa, Sub-Saharan Africa"
DEFAULT_INPUT_FILE = "safira.in"
DEFAULT_SHEET_NAME = "All_Indicators"
DEFAULT_DATA_FILE = "data/ssa_sai_all_indicators.xlsx"
DEFAULT_FIGURES_DIR = "figures"
DEFAULT_MODEL_WEIGHTS = "models/time_series_sai_model_weights.pth"
DEFAULT_MODEL_ASSETS = "models/time_series_sai_assets.pkl"
DEFAULT_LEGACY_MODEL = "models/time_series_sai_model.pth"

COUNTRY_ALIASES = {'ANGOLA': 'AGO',
 'AGO': 'AGO',
 'BENIN': 'BEN',
 'BEN': 'BEN',
 'BOTSWANA': 'BWA',
 'BWA': 'BWA',
 'BURKINA FASO': 'BFA',
 'BURKINA': 'BFA',
 'BFA': 'BFA',
 'BURUNDI': 'BDI',
 'BDI': 'BDI',
 'CABO VERDE': 'CPV',
 'CAPE VERDE': 'CPV',
 'CPV': 'CPV',
 'CAMEROON': 'CMR',
 'CMR': 'CMR',
 'CENTRAL AFRICAN REPUBLIC': 'CAF',
 'CAF': 'CAF',
 'CHAD': 'TCD',
 'TCD': 'TCD',
 'COMOROS': 'COM',
 'COM': 'COM',
 'DEMOCRATIC REPUBLIC OF CONGO': 'COD',
 'COD': 'COD',
 'DRC': 'COD',
 'CONGO-KINSHASA': 'COD',
 'CONGO': 'COG',
 'CONGO REPUBLIC': 'COG',
 'COG': 'COG',
 'CONGO-BRAZZAVILLE': 'COG',
 "COTE D'IVOIRE": 'CIV',
 'IVORY COAST': 'CIV',
 'CIV': 'CIV',
 'DJIBOUTI': 'DJI',
 'DJI': 'DJI',
 'EQUATORIAL GUINEA': 'GNQ',
 'GNQ': 'GNQ',
 'ERITREA': 'ERI',
 'ERI': 'ERI',
 'ESWATINI': 'SWZ',
 'SWAZILAND': 'SWZ',
 'SWZ': 'SWZ',
 'ETHIOPIA': 'ETH',
 'ETH': 'ETH',
 'GABON': 'GAB',
 'GAB': 'GAB',
 'GAMBIA': 'GMB',
 'THE GAMBIA': 'GMB',
 'GMB': 'GMB',
 'GHANA': 'GHA',
 'GHA': 'GHA',
 'GUINEA': 'GIN',
 'GIN': 'GIN',
 'GUINEA-BISSAU': 'GNB',
 'GNB': 'GNB',
 'KENYA': 'KEN',
 'KEN': 'KEN',
 'LESOTHO': 'LSO',
 'LSO': 'LSO',
 'LIBERIA': 'LBR',
 'LBR': 'LBR',
 'MADAGASCAR': 'MDG',
 'MDG': 'MDG',
 'MALAWI': 'MWI',
 'MWI': 'MWI',
 'MALI': 'MLI',
 'MLI': 'MLI',
 'MAURITANIA': 'MRT',
 'MRT': 'MRT',
 'MAURITIUS': 'MUS',
 'MUS': 'MUS',
 'MOZAMBIQUE': 'MOZ',
 'MOZ': 'MOZ',
 'NAMIBIA': 'NAM',
 'NAM': 'NAM',
 'NIGER': 'NER',
 'NER': 'NER',
 'NIGERIA': 'NGA',
 'NGA': 'NGA',
 'NIG': 'NGA',
 'RWANDA': 'RWA',
 'RWA': 'RWA',
 'SAO TOME AND PRINCIPE': 'STP',
 'SAO TOME': 'STP',
 'STP': 'STP',
 'SENEGAL': 'SEN',
 'SEN': 'SEN',
 'SEYCHELLES': 'SYC',
 'SYC': 'SYC',
 'SIERRA LEONE': 'SLE',
 'SLE': 'SLE',
 'SOMALIA': 'SOM',
 'SOM': 'SOM',
 'SOUTH AFRICA': 'ZAF',
 'ZAF': 'ZAF',
 'SOUTH SUDAN': 'SSD',
 'SSD': 'SSD',
 'SUDAN': 'SDN',
 'SDN': 'SDN',
 'TANZANIA': 'TZA',
 'TZA': 'TZA',
 'TOGO': 'TGO',
 'TGO': 'TGO',
 'UGANDA': 'UGA',
 'UGA': 'UGA',
 'ZAMBIA': 'ZMB',
 'ZMB': 'ZMB',
 'ZIMBABWE': 'ZWE',
 'ZWE': 'ZWE'}

SSA_COUNTRIES = ['AGO',
 'BEN',
 'BWA',
 'BFA',
 'BDI',
 'CMR',
 'CPV',
 'CAF',
 'TCD',
 'COM',
 'COG',
 'CIV',
 'COD',
 'DJI',
 'ERI',
 'ETH',
 'GAB',
 'GMB',
 'GHA',
 'GIN',
 'GNB',
 'KEN',
 'LSO',
 'LBR',
 'MDG',
 'MWI',
 'MLI',
 'MRT',
 'MUS',
 'MOZ',
 'NAM',
 'NER',
 'NGA',
 'RWA',
 'STP',
 'SEN',
 'SYC',
 'SLE',
 'SOM',
 'ZAF',
 'SSD',
 'SDN',
 'TGO',
 'UGA',
 'ZMB',
 'ZWE']

WORLD_BANK_INDICATORS = {'Secure_Internet_Servers': {'code': 'IT.NET.SECR',
                             'description': 'Secure servers (per 1 million people). Measures the '
                                            'number of distinct, publicly-trusted TLS/SSL '
                                            'certificates.'},
 'High_Tech_Exports_USD': {'code': 'TX.VAL.TECH.CD',
                           'description': 'High-technology exports (current US$). Total value of '
                                          'high-technology exports.'},
 'High_Tech_Exports_Pct_Manuf': {'code': 'TX.VAL.TECH.MF.ZS',
                                 'description': 'High-technology exports (% of manufactured '
                                                'exports).'},
 'R_and_D_Expenditure': {'code': 'GB.XPD.RSDV.GD.ZS',
                         'description': 'Research and development expenditure (% of GDP).'},
 'Fixed_Broadband_Subscriptions': {'code': 'IT.NET.BBND.P2',
                                   'description': 'Fixed broadband subscriptions (per 100 '
                                                  'people).'},
 'Mobile_Cellular_Subscriptions': {'code': 'IT.CEL.SETS.P2',
                                   'description': 'Mobile cellular subscriptions (per 100 '
                                                  'people).'},
 'Enrollment_Tertiary': {'code': 'SE.TER.ENRL',
                         'description': 'School enrollment, tertiary (gross), number.'},
 'Public_Ed_Expenditure': {'code': 'SE.XPD.TOTL.GD.ZS',
                           'description': 'Government expenditure on education, total (% of GDP).'},
 'Spending_on_Tertiary': {'code': 'SE.XPD.TERT.ZS',
                          'description': 'Expenditure on tertiary education (% of government '
                                         'expenditure on education). Coverage can be limited.'},
 'Educ_Attain_Secondary': {'code': 'SE.SEC.CUAT.UP.ZS',
                           'description': 'Educational attainment, at least completed upper '
                                          'secondary (% of population 25+).'},
 'Children_Out_of_School_Primary_Female': {'code': 'SE.PRM.UNER.FE',
                                           'description': 'Children out of school, primary, '
                                                          'female.'},
 'Children_Out_of_School_Primary_Male': {'code': 'SE.PRM.UNER.MA',
                                         'description': 'Children out of school, primary, male.'},
 'Gov_Expenditure_on_Ed_GovtExp_Pct': {'code': 'SE.XPD.TOTL.GB.ZS',
                                       'description': 'Government expenditure on education, total '
                                                      '(% of government expenditure).'},
 'Gov_Exp_Student_Primary_Pct_GDP_per_Cap': {'code': 'SE.XPD.PRIM.PC.ZS',
                                             'description': 'Government expenditure per student, '
                                                            'primary (% of GDP per capita).'},
 'Gov_Exp_Student_Secondary_Pct_GDP_per_Cap': {'code': 'SE.XPD.SECO.PC.ZS',
                                               'description': 'Government expenditure per student, '
                                                              'secondary (% of GDP per capita).'},
 'Gov_Exp_Student_Tertiary_Pct_GDP_per_Cap': {'code': 'SE.XPD.TERT.PC.ZS',
                                              'description': 'Government expenditure per student, '
                                                             'tertiary (% of GDP per capita).'},
 'Gross_Intake_Ratio_Grade1_Female': {'code': 'SE.PRM.GINT.FE.ZS',
                                      'description': 'Gross intake ratio in first grade of '
                                                     'primary, female (% of relevant age group).'},
 'Gross_Intake_Ratio_Grade1_Male': {'code': 'SE.PRM.GINT.MA.ZS',
                                    'description': 'Gross intake ratio in first grade of primary, '
                                                   'male (% of relevant age group).'},
 'Literacy_Rate_Adult_Female': {'code': 'SE.ADT.LITR.FE.ZS',
                                'description': 'Literacy rate, adult female (% of females ages 15 '
                                               'and above).'},
 'Literacy_Rate_Adult_Male': {'code': 'SE.ADT.LITR.MA.ZS',
                              'description': 'Literacy rate, adult male (% of males ages 15 and '
                                             'above).'},
 'Literacy_Rate_Adult_Total': {'code': 'SE.ADT.LITR.ZS',
                               'description': 'Literacy rate, adult total (% of people ages 15 and '
                                              'above).'},
 'Literacy_Rate_Youth_Female': {'code': 'SE.ADT.1524.LT.FE.ZS',
                                'description': 'Literacy rate, youth female (% of females ages '
                                               '15-24).'},
 'Literacy_Rate_Youth_Male': {'code': 'SE.ADT.1524.LT.MA.ZS',
                              'description': 'Literacy rate, youth male (% of males ages 15-24).'},
 'Literacy_Rate_Youth_Total': {'code': 'SE.ADT.1524.LT.ZS',
                               'description': 'Literacy rate, youth total (% of people ages '
                                              '15-24).'},
 'Persistence_Last_Grade_Primary_Female': {'code': 'SE.PRM.PRSL.FE.ZS',
                                           'description': 'Persistence to last grade of primary, '
                                                          'female (% of cohort).'},
 'Persistence_Last_Grade_Primary_Male': {'code': 'SE.PRM.PRSL.MA.ZS',
                                         'description': 'Persistence to last grade of primary, '
                                                        'male (% of cohort).'},
 'Primary_Completion_Rate_Female': {'code': 'SE.PRM.CMPT.FE.ZS',
                                    'description': 'Primary completion rate, female (% of relevant '
                                                   'age group).'},
 'Primary_Completion_Rate_Male': {'code': 'SE.PRM.CMPT.MA.ZS',
                                  'description': 'Primary completion rate, male (% of relevant age '
                                                 'group).'},
 'Primary_Completion_Rate_Total': {'code': 'SE.PRM.CMPT.ZS',
                                   'description': 'Primary completion rate, total (% of relevant '
                                                  'age group).'},
 'Progression_Secondary_Female': {'code': 'SE.SEC.PROG.FE.ZS',
                                  'description': 'Progression to secondary school, female (%).'},
 'Progression_Secondary_Male': {'code': 'SE.SEC.PROG.MA.ZS',
                                'description': 'Progression to secondary school, male (%).'},
 'Pupil_Teacher_Ratio_Primary': {'code': 'SE.PRM.ENRL.TC.ZS',
                                 'description': 'Pupil-teacher ratio, primary.'},
 'Repeaters_Primary_Female': {'code': 'SE.PRM.REPT.FE.ZS',
                              'description': 'Repeaters, primary, female (% of female '
                                             'enrollment).'},
 'Repeaters_Primary_Male': {'code': 'SE.PRM.REPT.MA.ZS',
                            'description': 'Repeaters, primary, male (% of male enrollment).'},
 'School_Enrollment_Preprimary_Gross': {'code': 'SE.PRE.ENRR',
                                        'description': 'School enrollment, preprimary (% gross).'},
 'School_Enrollment_Primary_Gross': {'code': 'SE.PRM.ENRR',
                                     'description': 'School enrollment, primary (% gross).'},
 'School_Enrollment_Primary_Net': {'code': 'SE.PRM.NENR',
                                   'description': 'School enrollment, primary (% net).'},
 'School_Enrollment_Primary_Gender_Parity': {'code': 'SE.ENR.PRIM.FM.ZS',
                                             'description': 'School enrollment, primary (gross), '
                                                            'gender parity index (GPI).'},
 'School_Enrollment_Prim_Sec_Gender_Parity': {'code': 'SE.ENR.PRSC.FM.ZS',
                                              'description': 'School enrollment, primary and '
                                                             'secondary (gross), gender parity '
                                                             'index (GPI).'},
 'School_Enrollment_Secondary_Gross': {'code': 'SE.SEC.ENRR',
                                       'description': 'School enrollment, secondary (% gross).'},
 'School_Enrollment_Secondary_Net': {'code': 'SE.SEC.NENR',
                                     'description': 'School enrollment, secondary (% net).'},
 'School_Enrollment_Tertiary_Gross': {'code': 'SE.TER.ENRR',
                                      'description': 'School enrollment, tertiary (% gross).'},
 'Trained_Teachers_Primary': {'code': 'SE.PRM.TCAQ.ZS',
                              'description': 'Trained teachers in primary education (% of total '
                                             'teachers).'},
 'Unemployment_Total': {'code': 'SL.UEM.TOTL.ZS',
                        'description': 'Unemployment, total (% of total labor force) (modeled ILO '
                                       'estimate).'},
 'Unemployment_Female': {'code': 'SL.UEM.TOTL.FE.ZS',
                         'description': 'Unemployment, female (% of female labor force) (modeled '
                                        'ILO estimate).'},
 'Unemployment_Male': {'code': 'SL.UEM.TOTL.MA.ZS',
                       'description': 'Unemployment, male (% of male labor force) (modeled ILO '
                                      'estimate).'},
 'Labor_Force_Participation': {'code': 'SL.TLF.CACT.ZS',
                               'description': 'Labor force participation rate, total (% of total '
                                              'population ages 15+).'},
 'Youth_Unemployment': {'code': 'SL.UEM.1524.ZS',
                        'description': 'Youth unemployment (% of total labor force ages 15-24).'},
 'Employment_in_Industry': {'code': 'SL.IND.EMPL.ZS',
                            'description': 'Employment in industry (% of total employment).'},
 'Employment_in_Agriculture': {'code': 'SL.AGR.EMPL.ZS',
                               'description': 'Employment in agriculture (% of total employment).'},
 'Self_Employed': {'code': 'SL.EMP.SELF.ZS',
                   'description': 'Self-employed, total (% of total employment).'},
 'Labor_Force_Female_Pct': {'code': 'SL.TLF.TOTL.FE.ZS',
                            'description': 'Labor force, female (% of total labor force).'},
 'Labor_Force_Total': {'code': 'SL.TLF.TOTL.IN', 'description': 'Labor force, total.'},
 'Population_Youth': {'code': 'SP.POP.1564.TO', 'description': 'Population ages 15-64 (total).'},
 'Population_Growth': {'code': 'SP.POP.GROW', 'description': 'Population growth (annual %).'},
 'Urban_Pop_Growth': {'code': 'SP.URB.GROW', 'description': 'Urban population growth (annual %).'},
 'Population_0_14_Pct': {'code': 'SP.POP.0014.TO.ZS',
                         'description': 'Population ages 0-14 (% of total population).'},
 'Population_15_64_Pct': {'code': 'SP.POP.1564.TO.ZS',
                          'description': 'Population ages 15-64 (% of total population).'},
 'GDP_Growth': {'code': 'NY.GDP.MKTP.KD.ZG', 'description': 'GDP growth (annual %).'},
 'GDP_Per_Capita': {'code': 'NY.GDP.PCAP.CD', 'description': 'GDP per capita (current US$).'},
 'Foreign_Direct_Investment': {'code': 'BX.KLT.DINV.WD.GD.ZS',
                               'description': 'Foreign direct investment, net inflows (% of GDP).'},
 'Gross_Capital_Formation': {'code': 'NE.GDI.TOTL.ZS',
                             'description': 'Gross capital formation (% of GDP).'},
 'Inflation_Consumer_Prices': {'code': 'FP.CPI.TOTL.ZG',
                               'description': 'Inflation, consumer prices (annual %).'},
 'GINI_Index': {'code': 'SI.POV.GINI',
                'description': 'GINI index (World Bank estimate). 0=perfect equality, 100=perfect '
                               'inequality.'},
 'Electric_Power_Consumption': {'code': 'EG.USE.ELEC.KH.PC',
                                'description': 'Electric power consumption (kWh per capita).'},
 'Access_to_Electricity': {'code': 'EG.ELC.ACCS.ZS',
                           'description': 'Access to electricity (% of population).'},
 'Rural_Urban_Divide_Proxy': {'code': 'SP.RUR.TOTL.ZS',
                              'description': 'Rural population (% of total population)—used as a '
                                             'digital divide proxy.'},
 'Life_Expectancy_Birth': {'code': 'SP.DYN.LE00.IN',
                           'description': 'Life expectancy at birth (years).'},
 'Mortality_Rate_U5': {'code': 'SH.DYN.MORT',
                       'description': 'Mortality rate, under-5 (per 1,000 live births).'},
 'Gov_Effectiveness': {'code': 'GE.EST',
                       'description': 'Government effectiveness: Estimate (-2.5 = weak; +2.5 = '
                                      'strong).'},
 'Regulatory_Quality': {'code': 'RQ.EST',
                        'description': 'Regulatory quality estimate (-2.5 = weak; +2.5 = strong).'},
 'Rule_of_Law': {'code': 'RL.EST',
                 'description': 'Rule of law estimate (-2.5 = weak; +2.5 = strong).'},
 'Control_of_Corruption': {'code': 'CC.EST',
                           'description': 'Control of corruption estimate (-2.5 = weak; +2.5 = '
                                          'strong).'}}

DEFAULT_PLOTS = [
    "choropleth",
    "spaghetti",
    "pillar_heatmap",
    "box",
    "gdp_scatter",
    "gdp_scatter_2020",
    "gdp_scatter_highlight",
    "gdp_scatter_top10",
    "corr",
    "corr_lower",
    "slope",
    "radar",
    "umap",
    "forecast_diag",
    "nigeria_comparison",
    "nigeria_comparison_seaborn",
    "forecast_diag_zaf",
    "spaghetti_selected",
    "spaghetti_selected_alt",
    "future_projection",
]
